general:
  data_base_dir: /app/data
  version: 1.0
  description: "Rhabdomyosarcoma MYOD1 mutation (dicom in and labelmap in, json out)"

execute:
- FileStructureImporter
- WsiMagnificationExtractor
- Patho_RMS_MYOD1_Mutation_Runner
- DataOrganizer

modules:
  FileStructureImporter:
    input_dir: input_data
    structures:
      - $sid@instance/$type@dicom:mod=sm
      - $sid@instance/$type@png:mod=seg
    import_id: sid


# look through the pyramidal DICOM-WSI image and select the best magnification 
# level to use for the model (10x with +/- 2.0x tolerance)
#  WsiMagnificationExtractor:
#    target_magnification: 10
#    magnification_tolerance: 2.0
#    meta: 
#      mod: 'sm'
      

  # run the fractional model
  Patho_RMS_MYOD1_Mutation_Runner:
    meta: 
      mod: 'sm'

  
  DataOrganizer:
    targets:
    - json-->[i:sid]/myod1_mutation.json
