general:
  data_base_dir: /app/data
  version: 1.0
  description: "Binary Segmentation configuration for Rhabdomyosarcoma pathology segmentation (dicom in, dicom out)"

execute:
- DicomImporter
- WsiMagnificationExtractor
- Patho_RMS_Runner_Binary
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: True
    meta: 
      mod: 'sm'

# look through the pyramidal DICOM-WSI image and select the best magnification 
# level to use for the model (10x with +/- 2.0x tolerance)

  WsiMagnificationExtractor:
    target_magnification: 10
    magnification_tolerance: 2.0
    meta: 
      mod: 'sm'
      
  # run the binary segmentation model
  Patho_RMS_Runner_Binary:
    meta: 
      mod: 'sm'

  
  DataOrganizer:
    targets:
    - dicomseg:mod=seg-->[i:sid]/pathology_rms_binary.seg.dcm
